targets:
  $default:
    sources:
      - lib/**
      - test/**
      - assets/**
      - $package$
    builders:
      injectable_generator:injectable_builder:
        generate_for:
          - lib/**
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/**
      slang_build_runner:
        generate_for:
          - lib/**
          - assets/i18n/**
